<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alloca.Application\Alloca.Application.csproj" />
    <ProjectReference Include="..\Alloca.Domain\Alloca.Domain.csproj" />
    <ProjectReference Include="..\Alloca.Infra\Alloca.Infra.csproj" />
    <ProjectReference Include="..\Alloca.CrossCutting\Alloca.CrossCutting.csproj" />
  </ItemGroup>

</Project>
