<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.21" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alloca.Application\Alloca.Application.csproj" />
    <ProjectReference Include="..\Alloca.Domain\Alloca.Domain.csproj" />
    <ProjectReference Include="..\Alloca.Infra\Alloca.Infra.csproj" />
    <ProjectReference Include="..\Alloca.CrossCutting\Alloca.CrossCutting.csproj" />
  </ItemGroup>

</Project>
